[package]
name = "oxi"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "oxi"
path = "src/main.rs"

[target.'cfg(target_os = "macos")'.dependencies]
burn = { git = "https://github.com/tracel-ai/burn", branch = "main", default-features = false, features = ["std", "train", "wgpu", "metal", "autodiff", "fusion", "tch", "candle" ] }
burn-candle = { git = "https://github.com/tracel-ai/burn", branch = "main", features = ["metal"] }
burn-tch = { git = "https://github.com/tracel-ai/burn", branch = "main", default-features = false }

[target.'cfg(target_os = "linux")'.dependencies]
burn = { git = "https://github.com/tracel-ai/burn", branch = "main", default-features = false, features = ["std", "train", "ndarray", "autodiff", "fusion", "candle"] }
burn-candle = { git = "https://github.com/tracel-ai/burn", branch = "main" }
burn-ndarray = { git = "https://github.com/tracel-ai/burn", branch = "main" }

[dependencies]
burn-train = { git = "https://github.com/tracel-ai/burn", branch = "main", default-features = false, features = ["tui"] }
burn-cuda = { git = "https://github.com/tracel-ai/burn", branch = "main", optional = true }
clap = { version = "*", features = ["derive"] }
serde = { version = "*", features = ["derive"] }
serde_yaml = "*"
shakmaty = "*"
pgn-reader = { git = "https://github.com/marcusbuffett/rust-pgn-reader", branch = "master" }
tokio = { version = "*", features = ["full"] }
indicatif = "*"
anyhow = "*"
tracing = "*"
tracing-subscriber = "*"
tracing-appender = "*"
reqwest = { version = "*", features = ["json", "stream"] }
flate2 = "*"
zstd = "*"
once_cell = "*"
futures-util = "*"
num_cpus = "*"
rand = "*"
statrs = "*"
itertools = "*"
bincode = "*"
ratatui = { version = "0.29", default-features = false, features = ["crossterm"] }
crossterm = "0.28"
zip = "0.6"

[dev-dependencies]
tempfile = "*"
burn-autodiff = { git = "https://github.com/tracel-ai/burn", branch = "main" }
insta = "*"

[features]
default = []
metal = []
cuda = []
