[package]
name = "oxi"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "oxi"
path = "src/main.rs"

[target.'cfg(target_os = "macos")'.dependencies]
burn = { git = "https://github.com/tracel-ai/burn", branch = "main", default-features = false, features = ["std", "train", "wgpu", "metal", "autodiff", "fusion", "tch", "candle" ] }
burn-candle = { git = "https://github.com/tracel-ai/burn", branch = "main", features = ["metal"] }

[target.'cfg(target_os = "linux")'.dependencies]
burn = { git = "https://github.com/tracel-ai/burn", branch = "main", default-features = false, features = ["std", "train", "tch", "autodiff", "fusion", "candle", "cuda"] }
burn-candle = { git = "https://github.com/tracel-ai/burn", branch = "main", features = ["cuda"] }

[dependencies]
burn-train = { git = "https://github.com/tracel-ai/burn", branch = "main", default-features = false, features = ["tui"] }
burn-tch = { git = "https://github.com/tracel-ai/burn", branch = "main", default-features = false }
burn-cuda = { git = "https://github.com/tracel-ai/burn", branch = "main", optional = true }
clap = { version = "*", features = ["derive"] }
serde = { version = "*", features = ["derive"] }
serde_yaml = "*"
shakmaty = "*"
pgn-reader = { git = "https://github.com/marcusbuffett/rust-pgn-reader", branch = "master" }
tokio = { version = "*", features = ["full"] }
indicatif = "*"
anyhow = "*"
tracing = "*"
tracing-subscriber = "*"
tracing-appender = "*"
reqwest = { version = "*", features = ["json", "stream"] }
flate2 = "*"
zstd = "*"
once_cell = "*"
futures-util = "*"
num_cpus = "*"
rand = "*"
statrs = "*"
itertools = "*"
bincode = "*"
ratatui = { version = "0.29", default-features = false, features = ["crossterm"] }
crossterm = "0.28"

# [patch."https://github.com/tracel-ai/cubecl"]
# cubecl = { path = "./patches/cubecl/crates/cubecl" }
# cubecl-runtime = { path = "./patches/cubecl/crates/cubecl-runtime" }
# cubecl-ir = { path = "./patches/cubecl/crates/cubecl-ir" }
# cubecl-common = { path = "./patches/cubecl/crates/cubecl-common" }
# cubecl-core = { path = "./patches/cubecl/crates/cubecl-core" }

[dev-dependencies]
tempfile = "*"
burn-autodiff = { git = "https://github.com/tracel-ai/burn", branch = "main" }
insta = "*"

[features]
default = []
metal = []
cuda = []
