#!/usr/bin/env bash
set -euo pipefail

echo "==> Starting Oxi setup for Ubuntu (Lambda B200 friendly)"

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

APT_PACKAGES=(
  build-essential
  pkg-config
  libssl-dev
  curl
  wget
  rsync
  tmux
  git
)

echo "==> Installing system packages: ${APT_PACKAGES[*]}"
sudo apt update -qq
sudo apt install -y "${APT_PACKAGES[@]}"

if ! command -v cargo >/dev/null 2>&1; then
  echo "==> Installing Rust toolchain"
  curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
fi

if [ -f "$HOME/.cargo/env" ]; then
  # shellcheck source=/dev/null
  . "$HOME/.cargo/env"
fi

if ! command -v uv >/dev/null 2>&1; then
  echo "==> Installing uv"
  curl -LsSf https://astral.sh/uv/install.sh | sh
fi
export PATH="$HOME/.local/bin:$PATH"

cd "$REPO_ROOT"

echo "==> Preparing Python environment with uv"
uv python install 3.12
uv venv --python 3.12
uv sync --frozen --python 3.12

echo "==> Installing PyTorch 2.9.0 with CUDA 12.8 wheels"
UV_PYTHON="$REPO_ROOT/.venv/bin/python"
# Pin torch to the libtorch version oxi's `tch` crate (0.22.0) is built against:
# 2.9.0. Leaving it unpinned (or --upgrade) pulls the newest torch (e.g. 2.11),
# whose libtorch ABI is incompatible with tch at runtime — inference panics with
# `Cannot access data pointer of Tensor that doesn't have storage`. Keep this in
# lockstep with the `tch` version in Cargo.lock.
uv pip install --python "$UV_PYTHON" torch==2.9.0 torchvision torchaudio --index-url https://download.pytorch.org/whl/cu128

LIBTORCH_PATH="$("$UV_PYTHON" -c 'import torch; print(torch.__path__[0])')"
if [ ! -d "$LIBTORCH_PATH" ]; then
  echo "ERROR: Expected libtorch directory at $LIBTORCH_PATH but it was not found."
  exit 1
fi

BASHRC="$HOME/.bashrc"
MARKER_START="## Oxi setup (generated by setup_ubuntu.sh)"
MARKER_END="## End Oxi setup"

touch "$BASHRC"
if command -v python3 >/dev/null 2>&1; then
  python3 - "$BASHRC" <<'PY'
import sys
from pathlib import Path

path = Path(sys.argv[1])
text = path.read_text()
marker_start = "## Oxi setup (generated by setup_ubuntu.sh)"
marker_end = "## End Oxi setup"

start = text.find(marker_start)
if start != -1:
    end = text.find(marker_end, start)
    if end != -1:
        end = text.find("\n", end)
        if end == -1:
            end = len(text)
        new_text = text[:start].rstrip("\n")
        remainder = text[end+1:]
        if remainder and not remainder.startswith("\n"):
            remainder = "\n" + remainder
        if new_text and not new_text.endswith("\n"):
            new_text += "\n"
        path.write_text(new_text + remainder)
PY
fi

cat <<EOF >> "$BASHRC"

${MARKER_START}
if [ -f "\$HOME/.cargo/env" ]; then
  . "\$HOME/.cargo/env"
fi
export LIBTORCH="$LIBTORCH_PATH"
if [ -d "\$LIBTORCH/lib" ]; then
  export LD_LIBRARY_PATH="\$LIBTORCH/lib:\${LD_LIBRARY_PATH:-}"
fi
${MARKER_END}
EOF

echo ""
echo "==> Setup complete"
echo "    cargo version: $(cargo --version)"
echo "    uv version: $(uv --version)"
echo "    torch version: $("$UV_PYTHON" -c 'import torch; print(torch.__version__)')"
echo "    libtorch path: $LIBTORCH_PATH"
echo ""
echo "Restart your shell or run: source ~/.bashrc"
